### ISSUE TITLE
Disqus not working

### ISSUE THREAD

**Issue by xaviermarichal** [dim0627/hugo_theme_robust#15]
Using the theme, I get an issue with Disqus stating that 
"We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.".

Having searched for help, solution seems quite straightforward: 
 https://discuss.gohugo.io/t/disqus-unable-to-load/6519
and I was willing to test locally the changes of the two variables to absolute path.

But I did first a git update on Robust repo, and now I cannot find anymore these variables, which used to be in the _partials/.../single.html file.
I do not understand how you embed Disqus in this new version, but I'm still facing the same issue, shown here:
https://www.dropbox.com/s/a573otoq6ctqb1u/Screenshot%202017-05-31%2015.56.23.png?dl=0

**Comment by dim0627** [comment]
hmm, I could not reproduce your issue.
What are you using hugo version?

My environments is below.

``` sh
~/Develop/repositories/src/github.com/spf13/HugoBasicExample (*master) $ hugo version
Hugo Static Site Generator v0.21-DEV darwin/amd64 BuildDate: 2017-04-21T17:01:34+09:00
```

``` toml
baseurl = "http://hugo.spf13.com/"
title = "Hugo Themes"
author = "Steve Francia"
copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."
canonifyurls = true
paginate = 3
disqusShortname = "42-design-work"

[outputs]
page = [ "HTML", "AMP"]
```

**Comment by xaviermarichal** [comment]
My version is this one:
`Hugo Static Site Generator v0.20.7 darwin/amd64 BuildDate: 2017-05-17T18:03:01+02:00`

I'll try upgrading to 0.21 asap and let you know.

**Comment by xaviermarichal** [comment]
Upgraded:
`Hugo Static Site Generator v0.21 darwin/amd64 BuildDate: 2017-06-02T14:56:34+02:00`

but still the same effect. Here is my config:

languageCode = "en-us"
title = "My Very own -little- book review"
baseurl = "http://humoeursvertes.net/"

[Params]
  Author = "Bibi Grosso Modo"
  disqusShortname = "xaviermarichal"

**Comment by dim0627** [comment]
oh ok.
You should try this code.

config.toml
``` toml
languageCode = "en-us"
title = "My Very own -little- book review"
baseurl = "http://humoeursvertes.net/"
disqusShortname = "xaviermarichal"

[Params]
Author = "Bibi Grosso Modo"
```
